SHOW DATABASES;
USE DBMS_CE21_G11;

# 1
SELECT DEPTNO, COUNT(*) FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) = 0;

# 2
SELECT COUNT(empno),AVG(SAL),DEPTNO,JOB FROM EMP
GROUP BY DEPTNO,JOB;

# 3
SELECT MAX(SAL) FROM EMP
WHERE SAL IN 
(SELECT AVG(SAL) AS AVGSAL
FROM EMP
WHERE JOB != 'PRESIDENT'
GROUP BY JOB);

# 4
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;

# 5
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 3;

# 6
SELECT E.EMPNAME, E.DEPTNO, SAL
FROM EMP E
WHERE E.SAL IN
      (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO) ;

# 7
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < (SELECT AVG(SAL) FROM EMP);
