SHOW DATABASES;
USE DBMS_CE21_G11;
SHOW TABLES;

CREATE TABLE SUPPLIER (
	SCODE VARCHAR(5) PRIMARY KEY, 
    SNAME VARCHAR(30), 
    SCITY VARCHAR(20), 
    TURNOVER INTEGER
);
DESC SUPPLIER;

CREATE TABLE PART (
	PCODE VARCHAR(5) PRIMARY KEY,
    WEIGH DECIMAL(3,2),
    COLOR VARCHAR(10),
    COST INTEGER,
    SELLINGPRICE INTEGER
);
DESC PART;

CREATE TABLE SUPPLIER_PART(
	SCODE VARCHAR(5), 
    PCODE VARCHAR(5), 
    QTY INTEGER, 
    FOREIGN KEY (SCODE) REFERENCES SUPPLIER(SCODE), 
    FOREIGN KEY (PCODE) REFERENCES PART(PCODE)
);
DESC SUPPLIER_PART;

INSERT INTO SUPPLIER VALUES('S01','TOM','BOMBAY',50);
INSERT INTO SUPPLIER VALUES('S02','TONY','NEW YORK',NULL);
INSERT INTO SUPPLIER VALUES('S03','PETER','CHENNAI',80);
INSERT INTO SUPPLIER VALUES('S04','JACK','AHEMDABAD',120);
SELECT * FROM SUPPLIER;

INSERT INTO PART VALUES("P01", 28, "RED", 30, 1000);
INSERT INTO PART VALUES("P02", 30, "BLUE",20, 800);
INSERT INTO PART VALUES("P03", 32, "PURPLE", 40, 100);
INSERT INTO PART VALUES("P04", 40, "ORANGE", 70, 700);
SELECT * FROM PART;

INSERT INTO SUPPLIER_PART VALUES('S01',"P01",50);
INSERT INTO SUPPLIER_PART VALUES('S02','P02',150);
INSERT INTO SUPPLIER_PART VALUES('S03','P03',30);
INSERT INTO SUPPLIER_PART VALUES('S04','P04',100);
SELECT * FROM SUPPLIER_PART;

#1
SELECT SCODE, PCODE FROM SUPPLIER_PART ORDER BY SCODE, PCODE; 

#2
SELECT SNAME FROM SUPPLIER WHERE (SCITY = "BOMBAY" AND TURNOVER = 50);

#3
SELECT COUNT(SCODE) AS TOTAL_NO_OF_SUPPLIER FROM SUPPLIER;

#4
SELECT PCODE AS PART FROM PART WHERE (WEIGH BETWEEN 25 AND 35);

#5
SELECT SCODE AS SUPPLIER_NUMBER FROM SUPPLIER WHERE TURNOVER IS NULL;

#6
SELECT PCODE FROM PART WHERE COST IN (20, 30, 40);

#7
SELECT SUM(QTY) AS TOTAL_QUANTITY FROM SUPPLIER_PART WHERE PCODE = 'PO2';

#8
SELECT SUPPLIER.SNAME FROM SUPPLIER, SUPPLIER_PART 
WHERE SUPPLIER.SCODE = SUPPLIER_PART.SCODE AND PCODE = "P02";

#8
SELECT SNAME FROM SUPPLIER WHERE SCODE 
IN (SELECT SCODE FROM SUPPLIER_PART WHERE PCODE = 'P02');

#9
SELECT PCODE FROM PART WHERE COST>(SELECT AVG(COST) FROM PART);

#10
SELECT SNAME, TURNOVER FROM SUPPLIER ORDER BY TURNOVER DESC;

#11
SELECT SUM(WEIGH) FROM PART WHERE COLOR = 'BLACK';

#12
SELECT (SELLINGPRICE-COST) AS PROFIT FROM PART WHERE COST > 50;

#13
SELECT MAX(SELLINGPRICE) AS MAX_PRICE FROM PART GROUP BY COLOR;