SHOW DATABASES;
CREATE DATABASE SUPERMART;
USE SUPERMART;
SHOW TABLES;

CREATE TABLE CREDENTIALS (
    USERNAME VARCHAR(20) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);

INSERT INTO CREDENTIALS VALUES ("ADMIN", "123");
INSERT INTO CREDENTIALS VALUES ("USER1", "USER1");
INSERT INTO CREDENTIALS VALUES ("USER2", "USER2");
INSERT INTO CREDENTIALS VALUES ("USER3", "USER3");

SELECT * FROM CREDENTIALS;

CREATE TABLE SELLERS (
    SELLER_ID VARCHAR(10) PRIMARY KEY ,
    SELLER_USERNAME VARCHAR(15) ,
    SELLER_NAME VARCHAR(15) ,
    SELLER_MOBILE BIGINT ,
    SELLER_PASSWORD VARCHAR(15) , 
    GENDER ENUM("Male", "Female", "Prefer not to say")
);

INSERT INTO SELLERS VALUES ("S101", "ABC", "ASHOK", 3598410587, "ABC", "MALE");
INSERT INTO SELLERS VALUES ("S102", "PQRS", "AAYUSH", 7898410587, "PQRS", "MALE");
INSERT INTO SELLERS VALUES ("S103", "XYZ", "SAKSHI", 9884880587, "ABC", "FEMALE");
INSERT INTO SELLERS VALUES ("S104", "MN", "MAYUR", 3598410587, "ABC", "Prefer not to say");
INSERT INTO SELLERS VALUES ("S105", "OP", "KARAN", 7898410587, "PQRS", "MALE");
INSERT INTO SELLERS VALUES ("S106", "HS", "KHUSHI", 9884880587, "ABC", "FEMALE");

SELECT * FROM SELLERS;

CREATE TABLE PRODUCTS(
    P_ID VARCHAR(10) PRIMARY KEY,
    P_NAME VARCHAR(40),
    CATEGORY VARCHAR(20) ,
    COST_PRICE DECIMAL(10,2) ,
    SELLING_PRICE DECIMAL(10,2) ,
    STOCK INTEGER
);

INSERT INTO PRODUCTS VALUES('P101','OATS', 'Snacks',150,200,89);
INSERT INTO PRODUCTS VALUES('P102','MILK', 'Dairy',45,50,157);
INSERT INTO PRODUCTS VALUES('P103','KETCHUP', 'BAKERY',90,100,50);
INSERT INTO PRODUCTS VALUES('P104','RICE', 'Cereals',500,550,26);
INSERT INTO PRODUCTS VALUES('P105','BANANA', 'Produce',80,100,69);
INSERT INTO PRODUCTS VALUES('P106','JUICE', 'Beverages',100,125,46);
INSERT INTO PRODUCTS VALUES('P107','HAIR OIL', 'Personal Care',80,85,72);
SELECT * FROM PRODUCTS;

CREATE TABLE CATEGORY(
	CATEGORY_ID VARCHAR(20),
    CATEGORY_NAME VARCHAR(20),
    CATEGORY_QUANTITY INTEGER DEFAULT 0
);

INSERT INTO CATEGORY VALUES('C101','BAKERY', 1);
INSERT INTO CATEGORY VALUES('C102','BEVERAGES', 1);
INSERT INTO CATEGORY VALUES('C103','DAIRY', 1);
INSERT INTO CATEGORY VALUES('C104','PERSONAL CARE', 2);
INSERT INTO CATEGORY VALUES('C105','HOUSEHOLD ITEMS', 1);
INSERT INTO CATEGORY VALUES('C106','CEREALS', 1);
INSERT INTO CATEGORY VALUES('C107','SNACKS', 1);
INSERT INTO CATEGORY VALUES('C108','PRODUCE', 1);
SELECT * FROM CATEGORY;


SELECT CATEGORY, COUNT(CATEGORY) as Quantity FROM PRODUCTS GROUP BY CATEGORY;


CREATE TABLE CUSTOMER (
    C_ID VARCHAR(10) PRIMARY KEY,
    C_NAME VARCHAR(40) ,
    C_MOBILE BIGINT
);

INSERT INTO CUSTOMER VALUES ('C101', 'A', 12345);
INSERT INTO CUSTOMER VALUES ('C102', 'B', 54321);
INSERT INTO CUSTOMER VALUES ('C103', 'C', 67890);
INSERT INTO CUSTOMER VALUES ('C104', 'D', 098765);
INSERT INTO CUSTOMER VALUES ('C105', 'E', 12789);
INSERT INTO CUSTOMER VALUES ('C106', 'F', 98321);








ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pavilion';
flush PRIVILEGES;