# SET SQL_SAFE_UPDATES=0;

SHOW DATABASES;
USE DMBS_LAB;
SHOW TABLES;

# 1
SELECT NAME FROM CLIENT_MASTER;
SELECT * FROM CLIENT_MASTER;
SELECT NAME, CITY, STATE FROM CLIENT_MASTER;
SELECT DESCRIPTION FROM PRODUCT_MASTER;
SELECT NAME FROM CLIENT_MASTER WHERE CITY="MUMBAI" ;
SELECT SALESMANNAME FROM SALESMAN_MASTER WHERE SALAMT="3000" ;

# 2
UPDATE CLIENT_MASTER SET CITY = "BANGALORE" WHERE CLIENTNO = "C00005";
SELECT CLIENTNO, CITY FROM CLIENT_MASTER WHERE CLIENTNO = "C00005";

UPDATE CLIENT_MASTER SET BALDUE = "1000" WHERE CLIENTNO = "C00001";
SELECT CLIENTNO, BALDUE FROM CLIENT_MASTER WHERE CLIENTNO = "C00001";

UPDATE PRODUCT_MASTER SET COST_PRICE = "950" WHERE DESCRIPTION = "TROUSERS";
SELECT DESCRIPTION, COST_PRICE FROM PRODUCT_MASTER WHERE DESCRIPTION = "TROUSERS";

UPDATE SALESMAN_MASTER SET CITY = "PUNE";
SELECT * FROM SALESMAN_MASTER;

# 3
DELETE FROM SALESMAN_MASTER WHERE SALAMT=3500;
SELECT * FROM SALESMAN_MASTER;

DELETE FROM CLIENT_MASTER WHERE STATE="TAMIL NADU";
SELECT * FROM CLIENT_MASTER;

#4
ALTER TABLE CLIENT_MASTER ADD TELEPHONE INTEGER;
DESC CLIENT_MASTER;

ALTER TABLE PRODUCT_MASTER MODIFY SELLPRICE DECIMAL(10,2);
DESC PRODUCT_MASTER;

# 5
DROP TABLE CLIENT_MASTER;
SHOW TABLES;

# 6

ALTER TABLE SALESMAN_MASTER RENAME TO SMAN_MAST;
SHOW TABLES;