SHOW DATABASES;
USE DBMS_CE21_G11;
SHOW TABLES;

CREATE TABLE AUTHOR (
	AUTHOR_ID VARCHAR(5) PRIMARY KEY,
    LASTNAME VARCHAR(15),
    FIRSTNAME VARCHAR(15),
    EMAIL VARCHAR(40),
    CITY VARCHAR(15),
    COUNTRY VARCHAR(15)
);
DESC AUTHOR;

CREATE TABLE BOOK (
	BOOK_ID VARCHAR(5) PRIMARY KEY CHECK(BOOK_ID LIKE "B%"),
    BOOK_TITLE VARCHAR(50),
    COPIES INT CHECK(COPIES>2)
);
DESC BOOK;

CREATE TABLE AUTHOR_LIST (
	AUTHOR_ID VARCHAR(5),
    BOOK_ID VARCHAR(5),
    ROLE VARCHAR(15),
    PRIMARY KEY (AUTHOR_ID, BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);
DESC AUTHOR_LIST;

INSERT INTO AUTHOR VALUES("A0001", "Tripathi", "Amish", "amish.tripathi@gmail.com", "London", "United Kingdom");
INSERT INTO AUTHOR VALUES("A0002", "Christie", "Agatha", "agatha.christie@gmail.com", "London", "United Kingdom");
INSERT INTO AUTHOR VALUES("A0003", "Doyle", "Arthur Cona", "ac.doyle@gmail.com", "London", "United Kingdom");
INSERT INTO AUTHOR VALUES("A0004", "Verne", "Jules", "jules.verne@gmail.com", "Paris", "France");
SELECT * FROM AUTHOR;

INSERT INTO BOOK VALUES("B0001", "War of Lanka", 200);
INSERT INTO BOOK VALUES("B0002", "The Immortals of Meluha", 500);
INSERT INTO BOOK VALUES("B0003", "Murder on the Orient Express", 300);
INSERT INTO BOOK VALUES("B0004", "The Adventues of Sherlock Holmes", 400);
SELECT * FROM BOOK;


INSERT INTO AUTHOR_LIST VALUES("A0001", "B0001", "Writer");
INSERT INTO AUTHOR_LIST VALUES("A0001", "B0002", "Author");
INSERT INTO AUTHOR_LIST VALUES("A0002", "B0003", "Author");
INSERT INTO AUTHOR_LIST VALUES("A0003", "B0004", "Author");
SELECT * FROM AUTHOR_LIST;

ALTER TABLE AUTHOR_LIST ADD PUBLISHER VARCHAR(30); 
